#!/bin/sh
FORBIDDEN='binding.pry\|fail$'
git diff --cached --name-only | \
  GREP_COLOR='4;5;37;41' xargs grep --color --with-filename -n $FORBIDDEN \
  && echo '\nCOMMIT REJECTED. Found stray `binding.pry` or `fail` references.' \
  && exit 1
